
[server]
    Address = "127.0.0.1:9999" # web服务器侦听地址，若需要外网访问则填写本机网卡IP地址，防火墙开放此端口
    Password = "admin888" # 用于Client同步配置所需密码，运行后请勿修改此值，否则Client同步配置信息失败

[database]
       host = "127.0.0.1"
       port = "5432"
       user = "postgres"
       pass = "password"
       name = "goscan"
       type = "pgsql"
       charset = "utf-8"
       maxOpen = "100"
       createdAt = "create_at"
       updatedAt = "update_at"
       debug  = true # 是否打印sql执行语句

[nsq]
       SHttpHost = "127.0.0.1:10001" # Server消息队列HTTP服务地址，填写127.0.0.1地址即可，请勿对外开放
       CHttpHost = "127.0.0.1:10002" # Client消息队列HTTP服务地址，填写127.0.0.1地址即可，请勿对外开放
       STcpHost = "127.0.0.1:4150" # Server投递消息TCP地址，对外开放，填写本机网卡地址，防火墙开放此端口
       CTcpHost = "127.0.0.1:4151" # Client投递消息TCP地址，对外开放，填写本机网卡地址，防火墙开放此端口